#-----------------
# NametagEdit v3.0.2
#-----------------
# Development Builds: http://ci.playmc.cc/job/NametagEdit
# Source Code: http://www.github.com/sgtcaze/NametagEdit
#-----------------

# If "true", this will remove any formatting created in the tab list by prefixes / suffixes
# Do not set this to true if you already have a plugin that changes the tab list
TabListDisabled: false

# If enabled, this plugin will send small data MCStats.org.
MetricsEnabled: true

# If enabled, this plugin will format the chat
Chat:
  Enabled: false
  Format: "%prefix% %s %suffix%: %s"

# If enabled, NametagEdit will use database support
MySQL:
  Enabled: false
  Hostname: localhost
  Port: 3306
  Username: myUsername
  Password: myPassword
  Database: myDatabase

# This is for MySQL. Update each time on join, or on a timer?
# The "TimerInterval" will be in seconds
Updating:
  OnJoin: false
  OnTimer: true
  TimerInterval: 60