#-----------------
# NametagEdit v3.0.1
#-----------------
# Development Builds: http://ci.playmc.cc/job/NametagEdit
# Source Code: http://www.github.com/sgtcaze/NametagEdit
#-----------------

# If "true", this will remove any formatting created in the tab list by prefixes / suffixes
# Do not set this to true if you already have a plugin that changes the tab list
TabListDisabled: false

# If enabled, this plugin will send small data MCStats.org.
MetricsEnabled: true

# If enabled, this plugin will format the chat
Chat:
  Enabled: false
  Format: "%prefix% %s %suffix%: %s"
  
# If enabled, NametagEdit will use database support
MySQL:
  Enabled: false
  Hostname: localhost
  Port: 3306
  Username: myUsername
  Password: myPassword
  Database: myDatabase
  Updating:
    OnJoin: false # Update from the database on join?
    OnTimer: true # Update from the database on a timer?
      Interval: 60 # Seconds between updates